services:
  db:
    image: postgres:17
    container_name: echo_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - echo_network

volumes:
  postgres_data:

networks:
  echo_network:
    driver: bridge